---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-sources-volume
  labels:
    for: sources
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  nfs:
    # The address 192.168.99.1 is the Minikube gateway to the host. This way
    # not the container IP will be visible by the NFS server on the host machine,
    # but the IP address of the `minikube ip` command. You will need to
    # grant access to the `minikube ip` IP address.
    # TODO: This IP is not static.
    server: 192.168.99.1
    path: {{PWD}}
