replicaCount: 1

image:
  repository: shiftedreality/magento-kubernetes-components-php
  tag: 7.1-fpm
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

#service:
#  type: NodePort
#  port: 8001
#  nodePort: 30301

xdebugService:
  type: NodePort
  port: 8002
  nodePort: 30302

persistence:
  nfs:
    enabled: false

monolith:
  name: magento2
  deployment:
    nginxImage: nginx:1.9
    codeImage: shiftedreality/magento-kubernetes-components-php
    imageTag: 7.1-fpm
    imagePullPolicy: Always
global:
  checkout:
    enabled: false
    db:
      enabled: false
    service:
      type: NodePort
      nodePort: 30102
      port: 80
  monolith:
    service:
      type: NodePort
      nodePort: 30301
      port: 8001
    mysqlHost: magento-mysql
    volumeHostPath: /Users/user/Projects/magento2-kubernetes-for-developers

checkout:
  enabled: false
resources: {}
  # Uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  fullname: magento-mysql
  mysqlRootPassword: "1234"

redis:
  usePassword: false
  master:
    disableCommands: []
